### ISSUE TITLE
Carousel Tutorial (Unexpected end of input / bundle.js error)

### ISSUE THREAD

**Issue by elinfante** [Famous/engine#199] opened 2015-05-28 09:14 UTC
Hi, 

I have forked the Carousel Tutorial following the steps from the website. Everything worked like a charm.  But what I have realised is that sometimes when I start editing the files to understand how it works I get the following error in the console:

``
Uncaught SyntaxError: Unexpected end of input    -----------------------     bundle.js:1
``

As soon as I refresh the browser everything starts working again. I do not get it all the time just randomly. 
Any idea why this could happen? 

Thanks!

**Comment by alexanderGugel** [comment] 2015-05-28 16:54
Strange. Since refreshing the browser fixes the issue I assume that it is probably some weird browserify/ watchify issue. Can you check via `ps` if multiple instances of the dev script are running?

**Comment by michaelobriena** [comment] 2015-05-29 16:50
@elinfante I have seen this too and I think this has to do with what Alex mentioned.  Every time I clear all processes running on that port I seem to not have the issue anymore.

**Comment by FarhadG** [comment] 2015-06-08 18:55
Has anyone else encountered this? @elinfante, was @alexanderGugel suggestion helpful?

Lookin' forward to having this resolved.

@michaelobriena

**Comment by alexanderGugel** [comment] 2015-06-08 18:58
Browserify bug. If you can reproduce it, it should be filed as an issue there. Otherwise this should be closed.

**Comment by Morgantheplant** [comment] 2015-06-10 17:03
Closing this now

**Closed by Morgantheplant** 2015-06-10 17:03 UTC
Labels: question

**Comment by elinfante** [comment] 2015-06-10 17:08
Sorry for the late reply, I must say I get this issue every now and then, but I will try to do what Alexander suggests and I will get back to you If the problem persists.
