### ISSUE TITLE
Undefined node in dispatchUIEvent method

### ISSUE THREAD

**Issue by monapasan** [Famous/engine#246] opened 2015-06-07 23:40 UTC
I am trying to catch an event on Dom element's node:
https://gist.github.com/monapasan/a4480bcd2aeca1348157
In makeFooter method.
I also have a node on higher level and a scene. All of nodes have onReceive method  but none of those is triggered, if i click on element. And i also have this exceptions. The third object in queue should be node that was clicked, but it's undefined. It's absolutely possible that i doing something wrong. But in this case i don't understand what. I was trying onReceive method,GestureHandler as well as custom component,bun in all cases i get an exception.  
Could anyone explain, what is the problem ?

![image](https://cloud.githubusercontent.com/assets/10222766/8026590/18e007d4-0d7d-11e5-98c5-ad1dbda3c5e0.png)
![image](https://cloud.githubusercontent.com/assets/10222766/8026608/b193d708-0d7d-11e5-881d-bb1078a36b88.png)

**Comment by alexanderGugel** [comment] 2015-06-08 07:42
You're incorrectly overriding `onParentMount`. This is definitely an issue.

```javascript
SelectionView.prototype.onParentMount = function onMount(parent, id) {
    Node.prototype.onMount.call(this, parent, id);
```

should be 

```javascript
SelectionView.prototype.onParentMount = function onMount(parent, id) {
    return this.mount(parent, parentId + '/' + id);
```

or

```javascript
SelectionView.prototype.onParentMount = function onMount(parent, id) {
    return Node.prototype.onParentMount.call(this, parent, id);
```

I tried reproducing this, but couldn't get your example to work. I will try later today, but I'm pretty sure that there is a bug in the application code that results into the nodes not being mounted correctly (see above).

**Comment by monapasan** [comment] 2015-06-08 09:58
Yes, you are right!
 If i remove the whole OnParentMount handler it's seems to be work, but in this case onMount Event on Child don't trigered at all.
http://famous.org/docs/core/Node.html#onMount
if i get it right, this one should be trigered,when the child node was added to the node on higher level?
Or this should triggered only when node was mounted direct to the main scene?
And  also onMount event don't trigger on node level above even if it's direct child from scene?
I would be very grateful if you could explain it.

**Comment by alexanderGugel** [comment] 2015-06-08 10:09
I'm not entirely sure I understand what you mean by "onMount Event on Child don't trigered at all". `onMount` is just an alias function for `mount`. If the `onMount` function wouldn't be called at all, the node would not be mounted (nothing would work). Therefore I guess that you're not subscribing correctly for the onMount event.

```
MyNode.prototype.onMount = function(parent, myId) {
    this.mount(parent, myId);
    
    // MyNode has been mounted.    

    return this;
};
```

---------------------
Adding a custom component to the node in order to subscribe for the `onMount` event is problematic due to the fact that adding a component will result into the component's `onMount` function being called immediately (if the node is mounted). This is a known issue and is being addressed in #211 via the `onAdd` event.

**Comment by monapasan** [comment] 2015-06-08 12:54
Thank you,i think now i get what onMount means. I thought it's eventHandler which triggered first the node was rendered. 
But i also have an issue :
In my ParentNode class
```javascript
	ParentNodeClass.prototype.onMount = function(parent, myId) {
        // this will be invoked
    	this.mount(parent, myId);
        // my ParentNode has been mounted
    	return this;
	};
}
```
In ChildNode class:
```javascript
	ChildNodeClass.prototype.onMount = function onMount (parent, id) {
           // But this not
	   Node.prototype.onMount.call(this, parent, id); // or this.mount(parent, id)
	   // some that has to be executed
	   return this;
	};
```
If i understand it right, the Parent-Node's in this case should be call onMount function on subtree classes as well ?

**Comment by alexanderGugel** [comment] 2015-06-08 13:29
> If i understand it right, the Parent-Node's in this case should be call onMount function on subtree classes as well ?

`Node#onMount` is equivalent to `Node#mount`. Calling `Node#mount` results into the children's `onParentMount` function being called, which in turns results into their `Node#mount` function being called.

Specifically:

```js
Node.prototype.onParentMount = function onParentMount (parent, parentId, index) {
    return this.mount(parent, parentId + '/' + index);
};
```
(`Node#onParentMount`)

and 

```js
    i = 0;
    list = this._children;
    len = list.length;
    for (; i < len ; i++) {
        item = list[i];
        if (item && item.onParentMount) item.onParentMount(this, myId, i);
    }
```
(`Node#mount`)

So yes, calling `Node#onMount` "flows down the scene graph". Does that answer your question?

**Comment by monapasan** [comment] 2015-06-09 20:56
Sorry for late reply.
Yes, that answers my questions, Thank you for help!
I get it to work !
What i actually had to do is: 
```javascript
Node.prototype.onParentMount = function onParentMount (parent, parentId, index) {
    this.mount(parent, parentId + '/' + index);
    // do stuff
   return this;
};

```

Thank you a lot !

**Closed** 2015-06-09 20:59 UTC
Labels: help wanted, question
