### ISSUE TITLE
animation lag in hierarchical scenes

### ISSUE THREAD

**Issue by 42experts** [Famous/engine#190] opened 2015-05-26 21:44 UTC
I have a scene that consists of hierarchically nested nodes.  For instance:
- Background
  - Content
    - Header
      - Button

Each node has an associated DIV element displayed as a plain color panel.  I am adding Position component to the Content node, ad start an animation that moves Content alongside the X axis.  I expect that the entire subtree (Content-Header-Button) moves when I move its root node.  The subtree indeed moves, but it does not do it synchronously.  The Header seems to be one frame behind Content, and Button seems to be one frame behind Header, creating a weird wavy effect.  I assume there is a bug somewhere, which does not propagate position changes immediately down the render tree.

I recorded a short video illustrating the problem:
http://manumatix.com/dev/bugs/animation1/famous-animation-lag.mp4

You can try it live here:
http://manumatix.com/dev/bugs/animation1/live/html/try-device.html
(just click on the button in the top-right corner)

The entire code of this example can be downloaded here:
http://manumatix.com/dev/bugs/animation1/animation-lag-20150526.zip

**Comment by DnMllr** [comment] 2015-05-26 21:55
@42experts Thank you very much for the work you put into creating this test case. pr #58 will fix this along with a number of other issues, however, it isn't currently ready to be merged. You can expect the fix within the next week.

**Comment by 42experts** [comment] 2015-05-26 21:58
Much appreciated!

**Comment by michaelobriena** [comment] 2015-05-29 16:52
@42experts Thanks for all of the work making the videos and public examples.  Really makes our job super easy.

**Comment by oldschooljarvis** [comment] 2015-06-04 10:17
I found that adding a mesh to the child node(s) serves as an effective workaround in the interim.

##### Two nodes, each with one DOMElement component. Parent/child relationship: #####
![bugreproduction3-1_02](https://cloud.githubusercontent.com/assets/3048285/7981652/ed18b0ba-0a75-11e5-9ce2-a077066c4ac0.gif)

##### Same setup, but adding a *Mesh* component to the child node: #####
![bugreproduction3-2_02](https://cloud.githubusercontent.com/assets/3048285/7981653/eea69ee2-0a75-11e5-9f3e-72360b8158f5.gif)

###### Source: https://gist.github.com/oldschooljarvis/be1911d93234a4f3cdc8 ######

**Comment by 42experts** [comment] 2015-06-05 20:14
This issue is labeled as "enhancement", but really it is a critical bug for all applications that make serious use of DOM animations.  The end user perception is of a broken animation.  Please reconsider:)

**Comment by michaelobriena** [comment] 2015-06-05 20:40
This is hands down the biggest priority for us.  We have the feature done on the development branch @DnMllr pointed out but are going through a lot of testing scenarios because of how important this is.  We will landed this ASAP.

**Comment by 42experts** [comment] 2015-06-05 20:46
Awesome; thank you!

**Comment by FarhadG** [comment] 2015-06-08 18:53
What's the status on this issue and PR?  Lookin' forward to having this resolved.

@DnMllr @michaelobriena

**Comment by michaelobriena** [comment] 2015-06-11 20:27
@DnMllr Can you put in an update please?

**Comment by 42experts** [comment] 2015-06-16 16:50
Is there a release date with a definitive fix for this?  I've taken the risks of making a pretty ambitious project based on Famous, developed 70% of it on the beta version, then threw everything away when 1.0 came out, and now stuck with this...  Anything I can do to help accelerating this fix?  People are screaming at me, and not without a reason:-)

**Comment by 42experts** [comment] 2015-06-24 23:47
seems fixed in 0.6.2

**Comment by michaelobriena** [comment] 2015-07-07 00:04
Closing as this was fixed in 0.6

**Closed by michaelobriena** 2015-07-07 00:04 UTC
Labels: bug, in-progress
