### ISSUE TITLE
Node.setOpacity() values are not uniformly inherited across renderables

### ISSUE THREAD

**Issue by oldschooljarvis** [Famous/engine#222] opened 2015-06-03 11:42 UTC
Instances of **Mesh** seem to only reflect opacity correctly if the value is set directly on the node they are attached to. Instances on child nodes do not properly inherit opacity.

**DOMElement** doesn't seem to have a problem with this and works as one would expect.

Annotated visual explanation:
![famous-engine-opacitybug](https://cloud.githubusercontent.com/assets/3048285/7959040/0d9d33f8-09bb-11e5-8017-6887b969f752.png)

Full source to reproduce:
https://gist.github.com/oldschooljarvis/48648e203dfabe911b36#file-famous-engine-issue222-1

**Comment by alexanderGugel** [comment] 2015-06-03 11:53
We're currently making some drastic changes to the way we're [multiplying transform matrices](https://github.com/DnMllr/engine/tree/feature-systems). In order to achieve this, we set breakpoints on nodes, depending on the kind of renderable attached to them.

We're going to use the same breakpoint system for opacities. The main issue with opacity currently is that it is not being multiplied **at all**. This explains the opacity on GL nodes in your example.

The reason DOM nodes **seem** to have the correct opacity is that every ancestor node in your example has a DOMElement. Therefore the browser multiplies the opacities for us through the nested DOM.

We're working on a fix.

**Comment by oldschooljarvis** [comment] 2015-06-03 12:02
I just realized this after calling *depth4.getOpacity()* on my example above. Instead of 0.09, it returned 0.3. So yeah, the browser is definitely multiplying opacity values.

Seems I was thinking about the problem backwards. :)

**Comment by michaelobriena** [comment] 2015-06-04 17:54
As @alexanderGugel we are working on this and hope to get this in soon.  We will keep you posted.

**Comment by FarhadG** [comment] 2015-06-08 19:06
What's the status on this issue and its fix?

@alexanderGugel @michaelobriena

**Comment by alexanderGugel** [comment] 2015-06-08 19:23
I'm waiting til Dan's stuff is stable. I started an implementation a couple of times, it's not that hard, but it doesn't make sense if the future internal API isn't stable. So please leave this open.

**Comment by oldschooljarvis** [comment] 2015-06-12 18:25
Sorry for chiming in late here, I should have given this more thought a week ago.

>The main issue with opacity currently is that it is not being multiplied at all.

Will there be a way to exempt chosen descendant nodes from undergoing opacity multiplication? Not having this would almost be worse than having zero opacity multiplication anywhere.

I'm not sure what the aforementioned breakpoint system entails, but hopefully the requirement to have idiomatic nested DOM won't make this impossible.

**Comment by alexanderGugel** [comment] 2015-06-12 18:31
> Will there be a way to exempt chosen descendant nodes from undergoing opacity multiplication? Not having this would almost be worse than having zero opacity multiplication anywhere.

Currently there are no plans to account for that. The issue is that if you have a 50% transparent parent div, there is no way to reset the child's CSS opacity to something > 1.

The basic idea with the breakpoints is that nodes that have a DOMElement on them have a breakpoint. The transforms and opacities are then being multiplied accordingly to avoid the inversion that is currently taking place in the DOMRenderer.

**Comment by oldschooljarvis** [comment] 2015-06-12 19:17
>Currently there are no plans to account for that.

Does this mean that the GL side of things will ultimately behave the same as DOM in this respect? Aside from breaking uniformity, I don't see any compelling reason for GL having to suffer the same limitations. Arguably the scene graph's dependency on ```DOMElement``` limitations have already broken uniformity anyways.

To be clear, cascading opacity multiplication with GL is certainly desired (saves a ton of work), but only if there's a way to exempt select descendant nodes. Otherwise, it might make sense to just leave things the way they are, since one can manually multiply GL opacities now if desired.

>The issue is that if you have a 50% transparent parent div, there is no way to reset the child's CSS opacity to something > 1.

I see two ways to get around this:

1. Flat DOM (obviously not happening).
2. Break off undesirable cascading ancestor opacities into their own isolated ```<div>```. This breaks idiomatic DOM though, so probably also not happening.

-

Again, sorry for changing my tune on this. I should have given it more thought originally.

**Comment by alexanderGugel** [comment] 2015-06-12 19:21
I understand that not inheriting parent opacities (as an option) is a wanted feature, but I don't think this is something that should be accounted for in the Node's API. If you don't want the Mesh to inherit its parent opacity, you could still subclass Mesh and have a NOP in onOpacityChange. I understand that this is definitely not the best solution, but I don't see how we could account for this feature while accounting for the usual DOM limitation.

**Comment by jd-carroll** [comment] 2015-06-14 18:05
Can someone explain to me why you would want an "opt-out" behavior?  To me this doesn't make sense and breaks the inheritance of the scene graph.  If you want components under a shared parent to have different opacities, then why not set the opacity at their individual levels instead of the parent.  Or why not create an event broadcast from the shared parent that tells the sub-nodes to change the opacity on the desired components.

Alright, probably don't have to explain it, I understand the desire to have an "opt-out" or sticky components.  But I worry about the unintended behavior of the "opt-out".  Specifically when it comes to transitioning nodes in & out of focus. (How to override and override)

**Comment by oldschooljarvis** [comment] 2015-06-14 18:53
>Can someone explain to me why you would want an "opt-out" behavior? To me this doesn't make sense and breaks the inheritance of the scene graph.

Because while opacity inheritance is a nice convenience feature and probably the desired behavior in most cases, consigning all descendant nodes to the opacity of their parent is a bad thing if no mechanism exists to work around that.

That said, having a Node-level opt-out feature that simply doesn't work with ```DOMElement``` isn't desirable either. Therefore, what @alexanderGugel suggested - subclassing Mesh as a means of opting out of opacity inheritance with GL - is probably the best way to go.

>If you want components under a shared parent to have different opacities, then why not set the opacity at their individual levels instead of the parent.

In the absence of any opt-out mechanism or workaround at all, this is actually desirable.

**Comment by alexanderGugel** [comment] 2015-07-31 12:23
fixed in #307

**Closed by alexanderGugel** 2015-07-31 12:23 UTC
Labels: bug, in-progress
